# Generated by Django 4.1.1 on 2022-10-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lohandsoft_register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
